package org.com.drag.model;

import org.com.drag.common.util.Constants;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
/**
 * 
 * Copyright © 2016优易数据. All rights reserved.

 * @ClassName: UploadHistory

 * @Description: 上传数据实体

 * @author: jiaonanyue

 * @date: 2016年12月28日 下午4:37:03
 */
public class UploadHistory implements Serializable{
    /**
	
	 * @fieldName: serialVersionUID
	
	 * @fieldType: long
	
	 * @Description: TODO
	
	 */
	private static final long serialVersionUID = 1917493548359309648L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_history.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_history.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_history.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column upload_history.upload_user
     *
     * @mbggenerated
     */
    private Integer uploadUser;
    
    
    /**
     * 上传的路径
     */
    private String hdfsUrl;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_history.id
     *
     * @return the value of upload_history.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_history.id
     *
     * @param id the value for upload_history.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_history.file_name
     *
     * @return the value of upload_history.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_history.file_name
     *
     * @param fileName the value for upload_history.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_history.upload_time
     *
     * @return the value of upload_history.upload_time
     *
     * @mbggenerated
     */
    public String getUploadTime() {
        Calendar c = Calendar.getInstance();
        SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        String date = dateformat.format(uploadTime);
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_history.upload_time
     *
     * @param uploadTime the value for upload_history.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column upload_history.upload_user
     *
     * @return the value of upload_history.upload_user
     *
     * @mbggenerated
     */
    public Integer getUploadUser() {
        return uploadUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column upload_history.upload_user
     *
     * @param uploadUser the value for upload_history.upload_user
     *
     * @mbggenerated
     */
    public void setUploadUser(Integer uploadUser) {
        this.uploadUser = uploadUser;
    }

    public UploadHistory() {
    }

    public UploadHistory(String fileName, Date uploadTime, Integer uploadUser,String hdfsUrl) {
        this.fileName = fileName;
        this.uploadTime = uploadTime;
        this.uploadUser = uploadUser;
        this.hdfsUrl = hdfsUrl;
    }

	public String getHdfsUrl() {
		return hdfsUrl;
	}
    public String getHdfsUrl(UploadHistory uploadHistory) {
        return  Constants.getHdfsUrl().toString()+uploadHistory.getHdfsUrl();
    }
	public void setHdfsUrl(String hdfsUrl) {
		this.hdfsUrl = hdfsUrl;
	}

	@Override
	public String toString() {
		return "UploadHistory [id=" + id + ", fileName=" + fileName + ", uploadTime=" + uploadTime + ", uploadUser="
				+ uploadUser + ", hdfsUrl=" + hdfsUrl + "]";
	}
    
}